### ISSUE TITLE
Decoding crypto-sskr shard failing

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/URKit#1]
Prior to upgrading to 2.0.0 this was working fine:

`try? URDecoder.decode("ur:crypto-sskr/taadecgojlcybyadaevoemiadngdcwrewlvwdkwphldlztwtdtqzpafnzo")`

It now always returns nil.

Shard samples taken from [https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md#exampletest-vector](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md#exampletest-vector)

Do I need to update my sskr library?

**Comment by wolfmcnally** [comment]
I actually don't see that SSKR in the document above. I did recently update the document to fix the Bytewords word list alphabetization error, so it's possible your test data above is out of date. You don't need to update SSKR, just URKit.

**Comment by Fonta1n3** [comment]
@wolfmcnally Are you saying the examples [here](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md#exampletest-vector) are outdated?

**Comment by Fonta1n3** [comment]
Ah, I think I see the source of my confusion... I am testing against UR's that were created with the old URKit. Derp. Will recreate them and revert.

**Comment by Fonta1n3** [comment]
User error! :P
