### ISSUE TITLE
When I parse ur:bytes, the result is nil，what should I do

### ISSUE THREAD

**Issue by losedMemory** [BlockchainCommons/URKit#4]
ur:bytes/hkaodpcncxfwjzkpihhghsjzjzihjycxgtkpjzjyinjkiniocxjkihjykpjocxiyinjzihbkcncxjyisinjkcxiyinjzihcxiajljtjyhsinjtjkcxjljtjzkkcxjokpidjziniacxjeihkkjkcxhsjtiecxinjkcxjkhsiyihcxjyjlbkcncxieinjkjyjpinidkpjyihcxhsjnjljtiocxiajljkiniojtihjpjkbkcnbkglhsjnihftcxcysnkbbtutoymubkgdjljziniakkftcxeycxjliycxeobkfyihjpinkohsjyinjljtftcxjndleeetdidldydidldydidleydibkfgjljpjnhsjyftcxgdeyhggufdbkbkehfyesfgeneoeyeoftcxhtjokpidemeeihgdgmflhsgojngokoksknkpiyktkkisgsgegtkkfpknfxhtgtknjpeeiohsghhsjtfdkkflesjthsgegljsihgdhkfpfpjtfxfdimfdgygtflfdgohdktknehfpjsimglihhshsecfgjpjkglglehksjngmisfghgjteykofyjthfhtfyfefyjsimihguisfeeniyfegoieeeiafwbkbkfgeneyendyfwdyfwftcxhtjokpidemeejyhfgdjlihjefyfwisethfgheyfyjshgimghiygohketjninhgjsfejpeeengyfwkpidiyhsghgmgdfwehgefygukkgegyeygdfxidjpjngugmkojtkkjyknihgoeojpieglgmeeetenjphtfggueyflhffpjyidisjpfdieiykngygsjtjyfgfxjlinjejyksidksfgfleogohsjybkbkeyeofwdyeheseyenftcxhtjokpidemeehskphgflguhdjeihethshdjnjlemkpfpglkpfxhdgsfpgmioktenkseojsjnesfgflehiafpinhdkkgyinflihiyeyecgehsgrjtjshtiyjtfyehiegoeyjlfdihjlineeiofdechtkteoghgskoinjnfdjpfpjsiyfgeeiniegyhdgseciaethdksjshtkteheniejpgmksjkiykobkbkfxrdkene

```
func parseUrBytesCoordinationSetup(_ urString: String) -> (text: String?, error: String?) {
    guard let ur = try? UR(urString: urString), let decodedCbor = try? CBOR.init(ur.cbor.bytes),
          case let CBOR.data(data) = decodedCbor,
    let text = String(data: data, encoding: .utf8) else {
        return (nil, "Unable to decode the QR code into a text file.")
    }
    return (text, nil)
}

```

**Comment by wolfmcnally** [comment]
The encoded string is not valid UTF-8. Everything up to that point is working. If you switch the `encoding` parameter to `.ascii`, it will decode. Not to say that's what you want, but we never recommend developers use the "ur:bytes" type for *any* deployment purpose. So you'll need to talk to the developer and determine what they're really encoding and how to get it from the `Data` into some other usable form.
