### ISSUE TITLE
Single part ur is crashing URKit v14.0.2 encoder.

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/URKit#7]
I convert this string to a UR:
`let string = "UR:CRYPTO-OUTPUT/TAADMETAADMSOEADAOAOLFTAADDLOSADWKAOWKAXHDCLAOPTYAFDUROTBSTKCYTTRTWZGEPLOEGSBDPFFSCLSTWDLONTRHPTRERFHKRFTYZMVAAAHDCXRLDYPMCKRHLPLBBWROLTHGRLREJLVEBYHTOSSGEHCPWKEYHDGLHPBTLECWTSCEWKAHTAADEHOYAOAEAMTAADDYOTADLOCSDYYKAEYKAEYKAOYKAOCYTNWMAANEAXAAAYCYAMRYGSGETAADDLOSADWKAOWKAXHDCLAOWEOSCMYAGMVEGAJSFRDKWNRKBDDMPLFPATJSEOYKCSREQDRKNLJYLAFGBNWYDYVWAAHDCXWDBSGMZOBGGLWENYGUKSFHLGBBTYBNWSFMWZLFUERHSFKIIONLVLEHOXBTJEMEASAHTAADEHOYAOAEAMTAADDYOTADLOCSDYYKAEYKAEYKAOYKAOCYHGKBHYTPAXAAAYCYVYJPTBPMRSQZHHCW"`
 
`try? UR(urString: string)`

Which returns a valid UR.

I then get the attached crash when it passes to:
```
private func animateUr(ur: UR) {
        let encoder = UREncoder(ur, maxFragmentLen: 250)
        print("encoder.isSinglePart: \(encoder.isSinglePart)")
        
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
            guard let self = self else { return }
            
            let part = encoder.nextPart()
            let index = encoder.seqNum
            
            if index <= encoder.seqLen {
                self.parts.append(part.uppercased())
            } else {
                self.spinner.removeConnectingView()
                self.animate()
                timer?.invalidate()
                timer = Timer.scheduledTimer(timeInterval: 0.3, target: self, selector: #selector(self.animate), userInfo: nil, repeats: true)
            }
        }
    }
```

`print("encoder.isSinglePart: \(encoder.isSinglePart)")` prints `true`.

When I use the identical code on multipart URs it works fine, according to the code comments it should handle single part UR's.

<img width="1440" alt="Screenshot 2024-07-12 at 20 10 55" src="https://github.com/user-attachments/assets/50a119e0-b9ed-4b21-aad9-a465f4ce19c1">

**Comment by wolfmcnally** [comment]
This was discussed in DMs. Single-part URs should are not supported for multi-part encoding. If UREncoder returns `true` for `isSinglePart`, do not call `nextPart`: just display the single-part UR.
